### ISSUE TITLE
Rollup failed to resolve import "/assets//spritemap.031560e3"

### ISSUE THREAD

**Issue by Evan-13-bee** [SpiriitLabs/vite-plugin-svg-spritemap#17]
Hello, I'm using a plugin on a Vue 2 different projects and found that if I use a sprite in this format
       <svg>
         <use href="/__spritemap#icon-spirit" />
       </svg>
then I can't create a project build and I get an error on Vue2:
Rollup failed to resolve import "/assets//spritemap.031560e3"
or on Vue 3
Error: [vite]: Rollup failed to resolve import "/assetsspritemap.95b4c41a.svg" from "E:/github-projects/vue/src/App.vue".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
     at viteWarn (file:///E:/github-projects/vue/node_modules/vite/dist/node/chunks/dep-df561101.js:48142:27)
     at onRollupWarning (file:///E:/github-projects/vue/node_modules/vite/dist/node/chunks/dep-df561101.js:48174:9)
     at onwarn (file:///E:/github-projects/vue/node_modules/vite/dist/node/chunks/dep-df561101.js:47902:13)
     at file:///E:/github-projects/vue/node_modules/rollup/dist/es/shared/node-entry.js:24194:13
     at Object.logger [as onLog] (file:///E:/github-projects/vue/node_modules/rollup/dist/es/shared/node-entry.js:25867:9)
     at ModuleLoader.handleInvalidResolvedId (file:///E:/github-projects/vue/node_modules/rollup/dist/es/shared/node-entry.js:24780:26)
     at file:///E:/github-projects/vue/node_modules/rollup/dist/es/shared/node-entry.js:24740:26

How can I fix this and what is wrong with slashes?

**Comment by Applelo** [comment]
Can you try to  remove the backslash from the href attribute ?

```html
 <svg>
   <use href="__spritemap#icon-spirit" />
 </svg>
```

**Comment by Evan-13-bee** [comment]
@Applelo  
Deleted, but it did not help, the error is still the same, only now without a slash at the beginning
[vite]: Rollup failed to resolve import "assets//spritemap.031560e3"

**Comment by Applelo** [comment]
Can you send me your vite.config.ts/vite.config.js file ? I suspect some kind of path problem with Windows.

**Comment by Evan-13-bee** [comment]
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import VitePluginSvgSpritemap from '@spiriit/vite-plugin-svg-spritemap'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    VitePluginSvgSpritemap('src/icons/*.svg')]
})

```

**Comment by Evan-13-bee** [comment]
I solved the problem, 

```
      <svg>
        <use :xlink:href="'/__spritemap#sprite-spiriit'" />
      </svg>
```
Should have added this :xlink:
